### ISSUE TITLE
const and cgkedit compatibility

### ISSUE THREAD

**Issue by docu4all** [lisps/const#5]
Hi,
we are testing the const plugin and we notice that the CKGEdit plugin can´t manage the %% quotes for a given constant.
For example: <const> myname=Bob </const>  Name: %%myname%%
Under DWEdit the output is Name: Bob - works like a charme :)

CKGEdit instead substitutes the %%  with nowiki tags 

Is there any way to wrap the constant and make it work with CKGEdit?

Cheers

**Comment by derdrave** [comment]
Hi, we have the same issue.
I contacted the author of ckgedit, who said that it might be easier to let you fix it inside the const-plugin -->  [https://github.com/turnermm/ckgedit/issues/540](https://github.com/turnermm/ckgedit/issues/540)
 
Would it be possible to extend your function to also recognize the nowiki tag? 
 
Best regards

**Comment by Michaelsy** [comment]
I think it is not a good idea for the const plugin to use an already used syntax.

But the basic idea of the plugin is very good. +1!

**Comment by derdrave** [comment]
how about using §§ instead of %%?

I tried locally and it seems to work.. 
Just don't know if §§ has any other use in dokuwiki or even php...


but to be honest I also don't like that ckeditor changes %% to nowiki-tags...
and renaming %% to nowiki-tags in const-plugin seems also a bit too much...

**Comment by peterfromearth** [comment]
I added §§ as an addition to %%

**Comment by mastersoftestde** [comment]
Thank you so much @peterfromearth! We are really grateful for the change.

**Comment by derdrave** [comment]
Yes, thanks a lot @peterfromearth, this feature comes in really handy to us.

Best wishes
