### ISSUE TITLE
Escape "=" sign in value

### ISSUE THREAD

**Issue by listerr** [lisps/const#9]
Doesn't seem to work if you have "=" in the value, for example you want to build a URL:

<const>
C_URL=https://some.query.url/search?q=
</const>

Then later in the document I have a reference like:

`My URL = [[%%C_URL%%123456|123456]]`

Or even an SQL plugin query like:

`CONCAT('<a href="%%C_URL%%', reg.companyNumber, '">', reg.companyNumber, '</a>') AS companyNumber,`

It doesn't resolve if the value contains "=", but if I take this out, it works.

I tried various methods to escape the "=" but it didn't work:

`C_URL='https://some.query.url/search?q='`
`C_URL=https://some.query.url/search?q\=`
`C_URL=https://some.query.url/search?q\\=`

`C_URL=''https://some.query.url/search?q' . '=''`

**Comment by mko24** [comment]
Easy to fix: See Pullrequest #7

**Comment by peterfromearth** [comment]
should be fixed now with #7
